# Generated by Django 3.2.3 on 2021-05-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buffet_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffet_round', models.CharField(max_length=64)),
                ('charge', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='buffet_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('status', models.BooleanField()),
                ('buffet_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.buffet_round')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=11)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=11, null=True)),
                ('resb_no', models.CharField(max_length=11, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.customer')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=12)),
                ('tax', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='promotion_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=7)),
                ('promotion_name', models.CharField(max_length=32)),
                ('promotion_detail', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='resb_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='resbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_guest', models.IntegerField()),
                ('total_charge', models.FloatField()),
                ('payment_method', models.CharField(max_length=32)),
                ('promotion_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.promotion_type')),
                ('resb_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.customer_booking')),
            ],
        ),
        migrations.CreateModel(
            name='room_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=4)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='room_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check_in', models.DateTimeField()),
                ('date_check_out', models.DateTimeField()),
                ('number_guest', models.IntegerField()),
                ('total_charge', models.FloatField()),
                ('payment_method', models.CharField(max_length=32)),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.customer_booking')),
                ('promotion_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.promotion_type')),
            ],
        ),
        migrations.CreateModel(
            name='room_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_count', models.IntegerField()),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.room_booking')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room_available')),
            ],
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=5)),
                ('service_name', models.CharField(max_length=10)),
                ('charge', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('job_title', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='hotel',
        ),
        migrations.AddField(
            model_name='room_detail',
            name='service_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.service'),
        ),
        migrations.AddField(
            model_name='room_booking',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
        migrations.AddField(
            model_name='room_available',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room_type'),
        ),
        migrations.AddField(
            model_name='resbooking',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
        migrations.AddField(
            model_name='resb_detail',
            name='resb_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.resbooking'),
        ),
        migrations.AddField(
            model_name='resb_detail',
            name='table_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.buffet_table'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.room_booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hotel.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='resb_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.resbooking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
    ]
