# Generated by Django 3.2 on 2021-06-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buffet_table',
            old_name='round',
            new_name='buffet_round',
        ),
        migrations.RemoveField(
            model_name='buffet_round',
            name='round',
        ),
        migrations.AddField(
            model_name='buffet_round',
            name='buffet_round',
            field=models.CharField(choices=[('lunch', 'LUNCH'), ('dinner', 'DINNER')], default=False, max_length=64),
        ),
    ]
