# Generated by Django 3.2.3 on 2021-06-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='hotel.customer', unique=True),
        ),
    ]
