# Generated by Django 3.2 on 2021-06-02 21:25

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion_type',
            name='promotion_code',
            field=models.CharField(default=hotel.models.promotion_type.genID, max_length=7),
        ),
    ]
