# Generated by Django 3.2 on 2021-06-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resbooking',
            old_name='payment_method',
            new_name='paymentmethod',
        ),
    ]
