# Generated by Django 3.2 on 2021-06-02 22:41

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buffet_round',
            old_name='buffet_round',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='buffet_table',
            old_name='buffet_round',
            new_name='round',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=hotel.models.customer.genID, max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_booking',
            name='booking_no',
            field=models.CharField(default=hotel.models.customer_booking.bhID, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_booking',
            name='resb_no',
            field=models.CharField(default=hotel.models.customer_booking.brID, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=hotel.models.staff.genID, max_length=9),
        ),
    ]
