# Generated by Django 3.2 on 2021-06-05 12:33

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(choices=[('S', 'Staff'), ('A', 'Admin'), ('M', 'Manager'), ('R', 'Receptionist'), ('HS', 'Hotel Staff'), ('RS', 'Restaurant Staff')], default='S', max_length=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=hotel.models.Staff.genID, max_length=12, primary_key=True, serialize=False),
        ),
    ]
