# Generated by Django 3.2.3 on 2021-06-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resbooking',
            old_name='resb_no',
            new_name='no',
        ),
    ]
