# Generated by Django 3.2 on 2021-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_booking',
            name='booking_no',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
