# Generated by Django 3.2.3 on 2021-06-03 13:24

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buffet_round',
            old_name='buffet_round',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='buffet_table',
            old_name='buffet_round',
            new_name='round',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='promotion_type',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resbooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room_available',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room_booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room_type',
            name='id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=hotel.models.customer.genID, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_booking',
            name='booking_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.room_booking'),
        ),
        migrations.AlterField(
            model_name='customer_booking',
            name='resb_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.resbooking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion_type',
            name='promotion_code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resbooking',
            name='resb_no',
            field=models.CharField(default=hotel.models.resbooking.brID, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room_available',
            name='room_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='booking_no',
            field=models.CharField(default=hotel.models.room_booking.bhID, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='roomtype',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=hotel.models.staff.genID, max_length=9, primary_key=True, serialize=False),
        ),
    ]
