# Generated by Django 3.2.3 on 2021-06-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_resb_no_resbooking_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resbooking',
            old_name='no',
            new_name='resb_no',
        ),
    ]
