# Generated by Django 3.2 on 2021-06-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210606_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_detail',
            name='service_code',
        ),
        migrations.AddField(
            model_name='room_detail',
            name='service_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=10),
        ),
    ]
