# Generated by Django 3.2.3 on 2021-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_customer_booking_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('R', 'Receptionist'), ('HS', 'Hotel Staff'), ('RS', 'Restaurant Staff'), ('S', 'Staff')], default='Staff', max_length=5),
        ),
    ]
