# Generated by Django 3.2.3 on 2021-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_no_resbooking_resb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resbooking',
            name='eatdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='date_check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='date_check_out',
            field=models.DateField(),
        ),
    ]
