# Generated by Django 3.2 on 2021-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210606_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion_type',
            name='promotion_type',
            field=models.CharField(default='type', max_length=20),
        ),
    ]
