# Generated by Django 3.2.3 on 2021-06-05 11:07

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_staff_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=hotel.models.Staff.genID, max_length=12, primary_key=True, serialize=False),
        ),
    ]
