# Generated by Django 3.2.3 on 2021-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(choices=[('S', 'Staff'), ('A', 'Admin'), ('M', 'Manager'), ('R', 'Receptionist'), ('HS', 'Hotel Staff'), ('RS', 'Restaurant Staff')], default='S', max_length=5),
        ),
    ]
