# Generated by Django 3.2 on 2021-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resbooking',
            name='promotion_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='promotion_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
