# Generated by Django 3.2 on 2021-06-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210607_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
