# Generated by Django 3.2 on 2021-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion_type',
            name='promotion_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant')], default='Hotel', max_length=20),
        ),
    ]
